# Função para listar vinhos e deixar o código do looping mais clean
def listarVinhos():
    print("-------------------------------------------------------------------")
    print("Vinhos Tintos:")
    print("• Carbenet Sauvignon – R$ 100,00")
    print("• Pinot Noir – R$ 120,00")
    print("• Tinto Malbec – R$ 80,00")
    print("• Tinto Merlot – R$ 90,00")
    print("• Tinto Syrah – R$ 100,00")
    print("-------------------------------------------------------------------")
    print("Vinhos Brancos:")
    print("• Chardonnay – R$ 80,00")
    print("• Sauvignon Blanc – R$ 70,00")
    print("• Riesling – R$ 90,00")
    print("• Pinot Grigio – R$ 60,00")
    print("-------------------------------------------------------------------")
    print("Vinhos Rosés:")
    print("• Cabernet Franc – R$ 70,00")
    print("• Syrah – R$ 80,00")
    print("• Grenache – R$ 60,00")
    print("-------------------------------------------------------------------")

listarVinhos()